title: Lamorinda-Help-Documentation
description: This docs hosts Lamorinda application user guides
theme: just-the-docs

url: https://github.com/cs169
baseurl: "/lamorinda-spirit-van/help-documentation"
plugins:
  - jekyll-default-layout


just_the_docs:
  navigation:
    structure: nested

aux_links:
  Github Repo: https://github.com/cs169/lamorinda-spirit-van/

footer_content: "MIT Licensed | City of Lafayette, CA. All Rights Reserved. © 2025"